import Head from "next/head";

import Title from "antd/lib/typography/Title";

import MainContent from "./components/MainContent/MainContent";

export default function Home() {

  return (
    <>
      <Head>
        <title>Coordinate systems transform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"main-container"}>

        <Title className={"h1"}>
          <span className={"titleBlock"}>
            <span>Преобразование </span>
            <span>систем</span>
            <span>координат</span>
          </span>
        </Title>

        <MainContent />

      </div>
    </>
  );
}
